# -*- coding: utf-8 -*-
__version__ = '1.0'
__title__ = 'webbot'
__description__ = 'webbot'
__url__ = 'https://github.com/joelee2012/webbot'
__author__ = 'Joe Lee'
__author_email__ = 'lj_2005@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2021 Joe Lee'
__documentation__ = ''
